import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LANGUAGE_STORAGE_KEY = 'tracksnap.language.preference.v1';

const translations = {
  tr: {
    'language.title': 'Dil',
    'language.description': 'Uygulama dilini seç. Yeni diller daha sonra buraya eklenebilir.',
    'language.current': 'Türkçe',
    'language.turkish': 'Türkçe',
    'language.english': 'İngilizce',
    'language.turkishDescription': 'Uygulamayı Türkçe kullan.',
    'language.englishDescription': 'Uygulamayı İngilizce kullan.',
    'auth.eyebrow': 'TRACKSNAP // ERİŞİM',
    'auth.heroTitle': 'Yolun sosyal ağı.',
    'auth.heroCopy': 'Sürüşünü takip et, topluluğunu bul ve rotanı paylaş.',
    'auth.login': 'Giriş',
    'auth.signup': 'Kayıt Ol',
    'auth.email': 'E-posta',
    'auth.plate': 'Plaka',
    'auth.password': 'Şifre',
    'auth.passwordHint': 'En az 8 karakter',
    'auth.forgotPassword': 'Şifremi Unuttum',
    'auth.connecting': 'Bağlanıyor...',
    'auth.enter': "TRACKSNAP'e Gir",
    'auth.required': 'Zorunlu alan',
    'auth.fullName': 'Görünen Ad',
    'auth.vehicleType': 'Araç Türü',
    'auth.car': 'Otomobil',
    'auth.motorcycle': 'Motosiklet',
    'auth.vehicleModel': 'Araç Modeli',
    'auth.tuningStage': 'Modifikasyon Seviyesi',
    'auth.horsepower': 'Beygir Gücü',
    'auth.odometer': 'Mevcut KM',
    'auth.profilePhoto': 'Profil Fotoğrafı',
    'auth.garage': 'Garaj / Tuning Servisi',
    'auth.privacyNotice': 'KVKK Aydınlatma Metni',
    'auth.terms': 'Kullanım Koşulları',
    'auth.acceptTerms': 'Kullanım Koşullarını kabul ediyorum.',
    'auth.plateSearch': 'Tam plakam yazıldığında diğer kullanıcıların beni bulabilmesini istiyorum.',
    'auth.optional': 'İsteğe bağlı',
    'auth.creating': 'Hesap Oluşturuluyor...',
    'auth.createGarage': 'Garajımı Oluştur',
    'auth.authError': 'Kimlik doğrulama işlemi tamamlanamadı.',
    'auth.maxFile': 'En fazla 5 MB',
    'auth.quickProfiles': 'Hızlı Test Profilleri',
    'auth.odometerExample': 'Örn. 68420',
    'auth.photoPreview': 'Profil fotoğrafı önizleme',
    'auth.privacyBody1': 'Hesap, araç, plaka, profil ve servis verileri hesabını oluşturmak, topluluk özelliklerini sunmak ve güvenliği sağlamak için işlenir.',
    'auth.privacyBody2': 'Giriş yapmış kullanıcılar tam plakanı yazarak seni bulabilir. Toplu plaka listesi sunulmaz ve arama istekleri sınırlandırılır.',
    'auth.privacyBody3': 'Konum hassasiyeti, Canlı Harita plaka görünürlüğü ve sosyal profil alanlarını daha sonra Profil > Gizlilik bölümünden değiştirebilirsin.',
    'auth.termsBody1': 'Topluluk, sürüş ve araç kaydı özellikleri güvenli ve hukuka uygun biçimde kullanılmalıdır.',
    'auth.termsBody2': 'Yanıltıcı araç bilgisi, taciz, tehlikeli sürüş organizasyonu ve diğer kullanıcıların güvenliğini riske atan davranışlar hesap kısıtlamasına neden olabilir.',
    'auth.consentNote': 'Aydınlatma metni kayıt sırasında sunulur ve metin sürümü sistemde kaydedilir. Plaka arama tercihi daha sonra Gizlilik ayarlarından değiştirilebilir.',
    'settings.title': 'Ayarlar Merkezi',
    'settings.subtitle': 'Hesap, araç, konum ve güvenlik kontrolleri',
    'settings.appearance': 'Görünüm',
    'settings.appearanceDescription': 'Sistem temasını kullan veya açık ve koyu görünüm arasında seçim yap.',
    'settings.language': 'Dil',
    'settings.languageDescription': 'Uygulamanın görüntüleneceği dili seç.',
    'settings.privacy': 'Gizlilik ve Konum',
    'settings.privacyDescription': 'Canlı harita görünürlüğü, konum hassasiyeti ve güvenli bölge.',
    'settings.blocked': 'Engellenen Kullanıcılar',
    'settings.blockedDescription': 'Engellediğin sürücüleri gör ve engelleri yönet.',
    'settings.vehicle': 'Araç ve Profil',
    'settings.vehicleDescription': 'Araç bilgileri, bölge, garaj ve profil görünümü.',
    'settings.account': 'Hesap ve Veri Kontrolleri',
    'settings.accountDescription': 'Doğrulama, veri aktarımı, KVKK ve hesap silme.',
    'settings.security': 'Şifre ve Güvenlik',
    'settings.securityDescription': 'Hesap e-postası ve güvenli şifre değiştirme akışı.',
    'settings.appTheme': 'Uygulama Teması',
    'settings.themeDescription': 'Seçimin bu cihazda saklanır ve tüm ekranlara uygulanır.',
    'settings.system': 'Sistem',
    'settings.light': 'Açık',
    'settings.dark': 'Koyu',
    'settings.systemDescription': 'Cihazının açık veya koyu temasını otomatik takip eder.',
    'settings.lightDescription': 'Gündüz kullanımı için aydınlık ve yüksek okunabilirlik.',
    'settings.darkDescription': 'Gece sürüşleri için düşük parlaklıklı görünüm.',
    'settings.systemTheme': 'Sistem teması',
    'settings.lightTheme': 'Açık tema',
    'settings.darkTheme': 'Koyu tema',
    'settings.logout': 'Oturumu Kapat',
    'settings.logoutHint': 'Hesap verilerin silinmez; yalnızca bu cihazdaki oturum kapanır.',
    'settings.back': 'Ayarlar listesine dön',
    'settings.close': 'Ayarlar merkezini kapat',
    'nav.label': 'Ana navigasyon',
    'nav.map': 'Etkinlikler',
    'nav.liveMap': 'Canlı Harita',
    'nav.drive': 'Sürüş',
    'nav.forum': 'Akış',
    'nav.social': 'Sosyal',
    'nav.leaderboard': 'Sıralama',
    'nav.profile': 'Profil',
  },
  en: {
    'language.title': 'Language',
    'language.description': 'Choose the app language. More languages can be added here later.',
    'language.current': 'English',
    'language.turkish': 'Turkish',
    'language.english': 'English',
    'language.turkishDescription': 'Use the app in Turkish.',
    'language.englishDescription': 'Use the app in English.',
    'auth.eyebrow': 'TRACKSNAP // ACCESS',
    'auth.heroTitle': 'Your road. Your social network.',
    'auth.heroCopy': 'Track your drives, find your community and share your route.',
    'auth.login': 'Log In',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.plate': 'License Plate',
    'auth.password': 'Password',
    'auth.passwordHint': 'At least 8 characters',
    'auth.forgotPassword': 'Forgot Password',
    'auth.connecting': 'Connecting...',
    'auth.enter': 'Enter TRACKSNAP',
    'auth.required': 'Required field',
    'auth.fullName': 'Display Name',
    'auth.vehicleType': 'Vehicle Type',
    'auth.car': 'Car',
    'auth.motorcycle': 'Motorcycle',
    'auth.vehicleModel': 'Vehicle Model',
    'auth.tuningStage': 'Tuning Stage',
    'auth.horsepower': 'Horsepower',
    'auth.odometer': 'Current Odometer',
    'auth.profilePhoto': 'Profile Photo',
    'auth.garage': 'Garage / Tuning Shop',
    'auth.privacyNotice': 'Privacy Notice',
    'auth.terms': 'Terms of Use',
    'auth.acceptTerms': 'I accept the Terms of Use.',
    'auth.plateSearch': 'Allow other users to find me when they enter my full license plate.',
    'auth.optional': 'Optional',
    'auth.creating': 'Creating Account...',
    'auth.createGarage': 'Create My Garage',
    'auth.authError': 'Authentication could not be completed.',
    'auth.maxFile': 'Maximum 5 MB',
    'auth.quickProfiles': 'Quick Test Profiles',
    'auth.odometerExample': 'E.g. 68420',
    'auth.photoPreview': 'Profile photo preview',
    'auth.privacyBody1': 'Account, vehicle, license plate, profile and service data are processed to create your account, provide community features and maintain security.',
    'auth.privacyBody2': 'Signed-in users can find you by entering your full license plate. Bulk plate listings are not provided and search requests are rate-limited.',
    'auth.privacyBody3': 'You can change location precision, Live Map plate visibility and social profile fields later under Profile > Privacy.',
    'auth.termsBody1': 'Community, driving and vehicle record features must be used safely and lawfully.',
    'auth.termsBody2': 'Misleading vehicle information, harassment, dangerous driving events and conduct that risks other users may result in account restrictions.',
    'auth.consentNote': 'The privacy notice is shown during registration and its version is recorded. Plate search can be changed later in Privacy settings.',
    'settings.title': 'Settings',
    'settings.subtitle': 'Account, vehicle, location and security controls',
    'settings.appearance': 'Appearance',
    'settings.appearanceDescription': 'Follow the system theme or choose light and dark appearance.',
    'settings.language': 'Language',
    'settings.languageDescription': 'Choose the language used by the app.',
    'settings.privacy': 'Privacy & Location',
    'settings.privacyDescription': 'Live Map visibility, location precision and Safe Zone.',
    'settings.blocked': 'Blocked Users',
    'settings.blockedDescription': 'View blocked drivers and manage your block list.',
    'settings.vehicle': 'Vehicle & Profile',
    'settings.vehicleDescription': 'Vehicle details, region, garage and profile appearance.',
    'settings.account': 'Account & Data Controls',
    'settings.accountDescription': 'Verification, data export, privacy consent and account deletion.',
    'settings.security': 'Password & Security',
    'settings.securityDescription': 'Account email and secure password reset flow.',
    'settings.appTheme': 'App Theme',
    'settings.themeDescription': 'Your choice is saved on this device and applied to every screen.',
    'settings.system': 'System',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.systemDescription': "Follows your device's light or dark theme automatically.",
    'settings.lightDescription': 'A bright, highly readable appearance for daytime use.',
    'settings.darkDescription': 'A low-brightness appearance for night drives.',
    'settings.systemTheme': 'System theme',
    'settings.lightTheme': 'Light theme',
    'settings.darkTheme': 'Dark theme',
    'settings.logout': 'Log Out',
    'settings.logoutHint': 'Your account data is kept; only this device session is closed.',
    'settings.back': 'Back to settings list',
    'settings.close': 'Close settings',
    'nav.label': 'Main navigation',
    'nav.map': 'Events',
    'nav.liveMap': 'Live Map',
    'nav.drive': 'Drive',
    'nav.forum': 'Feed',
    'nav.social': 'Social',
    'nav.leaderboard': 'Leaderboard',
    'nav.profile': 'Profile',
  },
};

const defaultValue = {
  language: 'tr',
  setLanguage: () => undefined,
  t: (key) => translations.tr[key] ?? key,
};

const LanguageContext = createContext(defaultValue);

function getInitialLanguage() {
  if (typeof window === 'undefined') return 'tr';
  const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return stored === 'en' || stored === 'tr' ? stored : 'tr';
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key) => translations[language]?.[key] ?? translations.tr[key] ?? key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
