import { MapCard } from "../components/MapCard";
import { MapComposerPanel } from "../components/MapComposerPanel";
import { PinPanel } from "../components/PinPanel";

export function MapHubScreen({
  convoyFeedback,
  driverSearchResults,
  clearDraftRoute,
  draftLocation,
  joinCruise,
  likeGalleryImage,
  likePin,
  loadSpotPhotoFile,
  liveLocation,
  mapPickMode,
  mapPinErrors,
  mapPinFeedback,
  mapPinForm,
  mapPins,
  onApproveCruiseJoinRequest,
  onDeclineCruiseJoinRequest,
  onDeleteSpotPhoto,
  onDriverSearchChange,
  onInviteDriver,
  onReportSpotPhoto,
  onRemoveConvoyMember,
  onPickLocation,
  onSelectPin,
  onSetAttendeeTripStatus,
  onSetConvoyMemberRole,
  onSetConvoyLifecycleStatus,
  onUpdateConvoyDetails,
  onSetMapPickMode,
  onSetMapPinForm,
  onSetSpotPhotoForm,
  onSetWashForm,
  onSubmitMapPin,
  onSubmitSpotPhoto,
  onSubmitWashReview,
  onUseSelectedCoordinates,
  pickRouteBack,
  rateAttendee,
  selectedPin,
  selectedPinId,
  spotPhotoErrors,
  spotPhotoFeedback,
  spotPhotoForm,
  submitWashReview,
  user,
  washForm,
  washErrors,
  washFeedback,
}) {
  return (
    <section className="space-y-4">
      <MapCard
        pins={mapPins}
        selectedPinId={selectedPinId}
        onSelect={onSelectPin}
        user={user}
        liveLocation={liveLocation}
        draftLocation={draftLocation}
        draftRoutePath={mapPinForm.routePoints}
        mapPickMode={mapPickMode}
        onPickLocation={onPickLocation}
      />
      <PinPanel
        pin={selectedPin}
        user={user}
        convoyFeedback={convoyFeedback}
        driverSearchResults={driverSearchResults}
        spotPhotoErrors={spotPhotoErrors}
        spotPhotoFeedback={spotPhotoFeedback}
        spotPhotoForm={spotPhotoForm}
        washForm={washForm}
        washErrors={washErrors}
        washFeedback={washFeedback}
        onApproveCruiseJoinRequest={onApproveCruiseJoinRequest}
        onDeclineCruiseJoinRequest={onDeclineCruiseJoinRequest}
        onDeleteSpotPhoto={onDeleteSpotPhoto}
        onDriverSearchChange={onDriverSearchChange}
        onInviteDriver={onInviteDriver}
        onReportSpotPhoto={onReportSpotPhoto}
        onRemoveConvoyMember={onRemoveConvoyMember}
        onJoinCruise={joinCruise}
        onLikeGallery={likeGalleryImage}
        onLikePin={likePin}
        onRateAttendee={rateAttendee}
        onSetAttendeeTripStatus={onSetAttendeeTripStatus}
        onSetConvoyMemberRole={onSetConvoyMemberRole}
        onSetConvoyLifecycleStatus={onSetConvoyLifecycleStatus}
        onUpdateConvoyDetails={onUpdateConvoyDetails}
        onSpotPhotoFileChange={loadSpotPhotoFile}
        onSpotPhotoFormChange={onSetSpotPhotoForm}
        onSubmitSpotPhoto={onSubmitSpotPhoto}
        onSubmitWashReview={submitWashReview ?? onSubmitWashReview}
        onWashFormChange={onSetWashForm}
      />
      <MapComposerPanel
        draftLocation={draftLocation}
        feedback={mapPinFeedback}
        form={mapPinForm}
        errors={mapPinErrors}
        mapPickMode={mapPickMode}
        onClearRouteDraft={clearDraftRoute}
        onFormChange={onSetMapPinForm}
        onRemoveLastRoutePoint={pickRouteBack}
        onSetMapPickMode={onSetMapPickMode}
        onSubmit={onSubmitMapPin}
        onUseSelectedCoordinates={onUseSelectedCoordinates}
        user={user}
      />
    </section>
  );
}
